[package]
name = "ff_derive"
version = "0.1.0"
authors = ["Sean Bowe <ewillbefull@gmail.com>"]

[lib]
proc-macro = true

[dependencies]
syn = "0.11"
quote = "0.3"
num-bigint = "0.1"
num-traits = "0.1"
