before:
  hooks:
    - go mod tidy
builds:
- env:
    - CGO_ENABLED=0
  goarch:
    - amd64
    - arm
  goos:
    - darwin
    - linux
    - windows
    - freebsd
    - openbsd
    - solaris
archives:
- replacements:
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
release:
  prerelease: auto
