before:
  hooks:
    - make manifest
builds:
  -
    id: capp-mac
    env:
      - CGO_ENABLED=0
    binary: manager
    goos:
      - darwin
    goarch:
      - amd64
  -
    id: capp-linux
    env:
      - CGO_ENABLED=0
    binary: manager
    goos:
      - linux
    goarch:
      - amd64
      - arm64
release:
  extra_files:
    - glob: "./out/release/infrastructure-packet/v*/*"
archives:
- id: capp-linux
  builds:
    - capp-linux
- id: capp-mac
  builds:
    - capp-mac
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
publishers:
  -
    ids:
    - capp-linux
    name: "buildx"
    dir: "{{ dir .ArtifactPath }}/capp-linux_linux_{{ .Arch }}"
    cmd: 'docker buildx build --push --platform linux/{{ .Arch }} -t packethost/cluster-api-provider-packet:latest-{{ .Arch }} -t packethost/cluster-api-provider-packet:{{ .Tag }}-{{ .Arch }} -f ../../Dockerfile.goreleaser .'
