services:
  - docker

language: go
go:
  - "1.12.x"

script:
  - 'export GO111MODULE=on'
  - 'go mod download'
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then openssl aes-256-cbc -K $encrypted_1d073d5eb2c7_key -iv $encrypted_1d073d5eb2c7_iv
    -in scripts/artifactory.lic.enc -out scripts/artifactory.lic -d && make testacc'

matrix:
  fast_finish: true
  allow_failures:
    - go: tip