language: go

go:
  - 1.11.x
  - 1.12.x
  - master

services:
  - docker

jobs:
  include:
    - stage: compile
      script: make
    - stage: test
      script: make test
    - stage: integration
      if: env(TRAVIS_PULL_REQUEST) = false
      script:
        - openssl aes-256-cbc -K $encrypted_1d073d5eb2c7_key -iv $encrypted_1d073d5eb2c7_iv
          -in scripts/artifactory.lic.enc -out scripts/artifactory.lic -d
        - make testacc

matrix:
  fast_finish: true
  allow_failures:
    - go: master
