branches:
  only:
  - master
  - "/^v\\d+\\.\\d+\\.\\d+$/"
sudo: required
language: go
matrix:
  include:
  - go: 1.15.8
env:
  global:
  - secure: ApnvFLRwhoKNGdnzzx0EJhMfGdlFm1xwcZwrLnLNBASykNipAp2E9kfgXgH6zr5h2wdMS+P5F1lJhBsC+Q+kNXPecHAxvL8daH4eHW7bM3HQZOy4NkHVVgrsL5qaJ0ryui9ZTWrqhh62R857XWYLtlJMVtQKRwx4XJtmFKTU6UD7Zg47nb7rMswQfZDHlSZ8o3J+3RX94GiZ2yBzRPlTJRl0Y65+LE7qfMRSDLY4rNJAbGXAfUOCWEBAvfJLjvQ0VIh717VFKjQl9g3k7fnhVvYRygFntF4Gf0sv7dC2geAdg6dO3jFO7wwdntWkbKTbFcU+t75cCP4nFxMVSQZWYQtEi7utHOAifLWyEnyQBK9bTkOn0IsaHG34qPRUgld30U/ekGXKZMVRseKAHBkTbN8p9YdPvfmo+dfXC74WjNMg2NApw9XqDckPNm/vE2tm5wgxZOMabRcDcOrJs7JHTDfQ2+hkYkCQEWP7ZYckmWC8Z3PlVVT7llWfkDlFaH78Ac2pVFkhjKUtYZjiYs14JltHLES8xMJ17uyNIPaNMF83UBFZA35HVYfD3M6YnsdhsslI6k5/SwBg/F7RQSpVH2DBkn8heks2fE7QjHLq8/QdoI3O0ad2qJ1r55R9/3Ujl4CuwBb3aINe6706rkJ302viRpqFAHuE/4/6w9jKF9g=
  - secure: rnftG8cfbDXz3p6HtPVt5w5YfwINP7zuY8vF7ZVLm64IloXh/dFU0ATDcusSGU1fQbfi9JVA2TE7Isdpw4od9ZCWatJ6aaY0tgbYS/5/5khN0doW0EZ0WK/8EUpcFPv6eo5c8SWJt009n+Zhwg8kZkPIMdiW/IC3Bq5kFmycfV9iDApW7FB3wHin92PxBtf+wxJdY14L/Cx8BRRZM4Fa28AtPiWBKy5lvsV3MJA5KOP5AoEGztqhwsG25kEeMWCkpUbXH7OpA+glyA4mp9JeJpNFaJVRBmLVjEKmHo6JoSqPquWrXfX9F7KEWshXc2M5cuBbo9Po69MM5AUxKWxlrXckssl5T1xiLa5u3ST1jnM7xWZCQI39h5KIgNfljv3Iwymbm2+CS1byj/Q2ZI91Ov6SVyKkuiceXeIpFYO8RTHwghwSLagN3ZAfaE/AjoEO0Mkan5kOhxPDZRXB4Qx+wsxFGBNFrMNO74QmbLvFNzn2M72t+SJLRjKBS0KmbTQ71a0pKpJcAYeVxtJUKb5YGU9DkwNN34mvVqlyffXyQRSSAYAxZfygYb2Z9W9UwaDpeVyaafXLKHCSuHUYElitb7hoNeiAX602gD1J5eU0lG99c+BHlSTwDNw+HAoMqKOxNcymp5F8+Zyug7eCzbcm0g1Z3AeSTs7xVEL7Qm33QA8=
  - secure: wbY5JbotURyJJUbWxibBV5OVvkycsfpMZd7hVGlDzSS5/IDuw/5EAeqBUxfBVvdHx8ZV2fHA6lQ9ryAtWDNeiN9pJahCqBoQ4926RWAf33tdVk37vpMqJrOAw9qPshuT24vEG3z8etRKau+kHBNCTLABZEuzYUbeAO50qQGs2xhbZ/h2S6GlBRrFD+ebYrG5s25A/7rf8q1AONpeOTKWiUGCOx3rkY4BsBXO6nHeNgquz8ecdTD+8TZ2PN0Va8cJgR5ucq0ZwewwdO8w/ntuWP7mFMIqnjJXHnrkbhjTRg09FBwuu/wpwExynYWhnr1SlP/w5JYbLU3F4+ix9s7BQKPBCVTmGG0Xh96AORIiha1NzOj20ji+EzGPSHTKdWIyKQsZTXTSo9qFLnj62VxyUjxmViJj2fHa4fzGJbNAAAOXnY1wYQRXWlm/dafrebOsZDWHMnHrPgV8gtH7BhmRXsrb/k5eSNZgGpCDo26/fyDgeJnoZ7MMz0heZZilkjCtxDtcwYB9TVhKb6oTN0kfZvmpthjalm4TRBV0/VPgt0gTU4a1qpP6pvQn+KVI/262cqIAgAZ8krYTL2qNQzfXlLy1fi7jN0uEL8kG86yIvBkble8hjVHbXJI0J8bGWL3an+7AT6tYkSqImS+odfxiYnh+2tGJbks89fPbxn5RKJY=
  matrix:
  - GO_RELEASER_VERSION=v0.140.1
services:
- docker
before_install:
- GO111MODULE=off go get golang.org/x/lint/golint
- curl -L -o /tmp/goreleaser.tar.gz https://github.com/goreleaser/goreleaser/releases/download/${GO_RELEASER_VERSION}/goreleaser_Linux_x86_64.tar.gz
- sudo tar -xzf /tmp/goreleaser.tar.gz -C /usr/local/bin/ && sudo chmod +x /usr/local/bin/goreleaser
install:
-
script:
- make test-dirty
- make test
- make test-release
after_success:
- test -n "$TRAVIS_TAG" && docker login -u="$QUAYIO_USER" -p="$QUAYIO_SECRET" quay.io
deploy:
- provider: script
  skip_cleanup: true
  script: make clean release
  on:
    tags: true
    condition: "$TRAVIS_OS_NAME = linux"
