[package]
name = "zcash-mmr"
version = "0.1.0"
authors = ["NikVolf <nikvolf@gmail.com>"]
edition = "2018"

[dev-dependencies]
assert_matches = "1.3.0"
quickcheck = "0.8"

[dependencies]
derive_more = "0.15"
bigint = "4"
byteorder = "1"