[package]
name = "ff"
version = "0.2.0"
authors = ["Sean Bowe <ewillbefull@gmail.com>"]
description = "Library for building and interfacing with finite fields"
documentation = "https://docs.rs/ff/0.2.0/ff/"
homepage = "https://github.com/ebfull/ff"
license = "MIT/Apache-2.0"
repository = "https://github.com/ebfull/ff"

[dependencies]
rand = "0.3"
ff_derive = { version = "0.2.0", path = "ff_derive" }

[features]
u128-support = []
default = []
