version: '3'
services:
  artifactory:
    image: ${DOCKER_REGISTRY}/jfrog/artifactory-pro:${ARTIFACTORY_VERSION}
    environment:
      - JF_ROUTER_ENTRYPOINTS_EXTERNALPORT=${JF_ROUTER_ENTRYPOINTS_EXTERNALPORT}
    ports:
      - ${JF_ROUTER_ENTRYPOINTS_EXTERNALPORT}:${JF_ROUTER_ENTRYPOINTS_EXTERNALPORT} # 
      - 8081:8081 # for artifactory communication
    volumes:
      - ${ROOT_DATA_DIR}/artifactory/var:/var/opt/jfrog/artifactory
      - /etc/localtime:/etc/localtime:ro
    restart: always
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "10"
    ulimits:
      nproc: 65535
      nofile:
        soft: 32000
        hard: 40000
  mongodb:
    image: ${DOCKER_REGISTRY}/jfrog/xray-mongo:3.2.6
    ports:
      - ${JF_THIRD_PARTY_BIND_IP}:27017:27017
    entrypoint: /bin/bash -c "chmod 777 /data/logs; /entrypoint.sh --logpath /data/logs/xray-mongo.log --auth"
    volumes:
      - ${ROOT_DATA_DIR}/xray/var/data/mongodb/logs:/data/logs
      - ${ROOT_DATA_DIR}/xray/var/data/mongodb/configdb:/data/configdb
      - ${ROOT_DATA_DIR}/xray/var/data/mongodb/db:/data/db
      - /etc/localtime:/etc/localtime:ro
  router:
    image: ${DOCKER_REGISTRY}/jfrog/router:${ROUTER_VERSION}
    user: "${XRAY_USER}:${XRAY_USER}"
    environment:
      - JF_ROUTER_TOPOLOGY_LOCAL_REQUIREDSERVICETYPES=jfxr,jfxidx,jfxana,jfxpst
      - JF_ROUTER_ENTRYPOINTS_EXTERNALPORT=${JF_XRAY_ROUTER_ENTRYPOINTS_EXTERNALPORT}
    ports:
      - ${JF_XRAY_ROUTER_ENTRYPOINTS_EXTERNALPORT}:${JF_XRAY_ROUTER_ENTRYPOINTS_EXTERNALPORT} # for router communication
    volumes:
      - ${ROOT_DATA_DIR}/xray/var:/var/opt/jfrog/router
      - /etc/localtime:/etc/localtime:ro
    restart: always
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "10"
  xray-server:
    image: ${DOCKER_REGISTRY}/jfrog/xray-server:${XRAY_VERSION}
    volumes:
      - ${ROOT_DATA_DIR}/xray/var:/var/opt/jfrog/xray
      - /etc/localtime:/etc/localtime:ro
    restart: always
    network_mode: service:router
    ulimits:
      nproc: 65535
      nofile:
        hard: 40000
        soft: 32000
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "10"
  xray-indexer:
    image: ${DOCKER_REGISTRY}/jfrog/xray-indexer:${XRAY_VERSION}
    volumes:
      - ${ROOT_DATA_DIR}/xray/var:/var/opt/jfrog/xray
      - /etc/localtime:/etc/localtime:ro
    restart: always
    network_mode: service:router
    ulimits:
      nproc: 65535
      nofile:
        hard: 40000
        soft: 32000
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "10"
  xray-analysis:
    image: ${DOCKER_REGISTRY}/jfrog/xray-analysis:${XRAY_VERSION}
    volumes:
      - ${ROOT_DATA_DIR}/xray/var:/var/opt/jfrog/xray
      - /etc/localtime:/etc/localtime:ro
    restart: always
    network_mode: service:router
    ulimits:
      nproc: 65535
      nofile:
        hard: 40000
        soft: 32000
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "10"
  xray-persist:
    image: ${DOCKER_REGISTRY}/jfrog/xray-persist:${XRAY_VERSION}
    volumes:
      - ${ROOT_DATA_DIR}/xray/var:/var/opt/jfrog/xray
      - /etc/localtime:/etc/localtime:ro
    restart: always
    network_mode: service:router
    ulimits:
      nproc: 65535
      nofile:
        hard: 40000
        soft: 32000
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "10"
  rabbitmq:
    image: ${DOCKER_REGISTRY}/jfrog/xray-rabbitmq:3.8.3-management
    hostname: $HOST_ID
    entrypoint: ""
    command: /bin/bash -c " (/setRabbitCluster.sh &) && docker-entrypoint.sh 'rabbitmq-server'"
    ports:
      - ${JF_THIRD_PARTY_BIND_IP}:5672:5672
      - 15672:15672
      - 4369:4369
      - ${JF_THIRD_PARTY_BIND_IP}:25672:25672
    volumes:
      - ${ROOT_DATA_DIR}/xray/app/third-party/rabbitmq/setRabbitCluster.sh:/setRabbitCluster.sh
      - ${ROOT_DATA_DIR}/xray/app/third-party/rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ${ROOT_DATA_DIR}/xray/var/data/rabbitmq:/var/lib/rabbitmq
      - /etc/localtime:/etc/localtime:ro
    restart: always
    extra_hosts:
      - "${JF_SHARED_RABBITMQ_ACTIVE_NODE_NAME}:${JF_SHARED_RABBITMQ_ACTIVE_NODE_IP}"
    environment:
      - JF_SHARED_RABBITMQ_ACTIVE_NODE_NAME=${JF_SHARED_RABBITMQ_ACTIVE_NODE_NAME}
      - JF_SHARED_RABBITMQ_CLEAN=N # should be in sync with shared.rabbitMq.clean
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "10"
  postgres:
    image: ${DOCKER_REGISTRY}/postgres:12.5-alpine
    environment:
      - POSTGRES_HOME="/postgres"
      - POSTGRES_PASSWORD=__REPLACE_POSTGRES_PASSWORD__
    ports:
      - 5432:5432
    volumes:
      - ${ROOT_DATA_DIR}/artifactory/var/data/postgres/data:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
    restart: always
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "10"
    ulimits:
      nproc: 65535
      nofile:
        soft: 32000
        hard: 40000
