apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: controller-manager
    controller-tools.k8s.io: "1.0"
  name: system
---
apiVersion: v1
kind: Service
metadata:
  name: controller-manager-service
  namespace: system
  labels:
    control-plane: controller-manager
    controller-tools.k8s.io: "1.0"
spec:
  selector:
    control-plane: controller-manager
    controller-tools.k8s.io: "1.0"
  ports:
  - port: 443
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: controller-manager
  namespace: system
  labels:
    control-plane: controller-manager
    controller-tools.k8s.io: "1.0"
spec:
  selector:
    matchLabels:
      control-plane: controller-manager
      controller-tools.k8s.io: "1.0"
  serviceName: controller-manager-service
  template:
    metadata:
      labels:
        control-plane: controller-manager
        controller-tools.k8s.io: "1.0"
    spec:
      containers:
      - command:
        - /manager
        image: SET_BY_PATCH
        imagePullPolicy: IfNotPresent
        name: manager
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: PACKET_API_KEY
          valueFrom:
            secretKeyRef:
              name: credentials
              key: apiKey
        - name: PACKET_PROJECT_ID
          valueFrom:
            secretKeyRef:
              name: credentials
              key: projectID
        volumeMounts:
        - mountPath: /etc/machineconfig
          name: configs
          readOnly: true
        resources:
          limits:
            cpu: 100m
            memory: 30Mi
          requests:
            cpu: 100m
            memory: 20Mi
      terminationGracePeriodSeconds: 10
      volumes:
      - name: configs
        configMap:
          name: machine-setup
---
apiVersion: v1
kind: Secret
metadata:
  name: credentials
  namespace: system
stringData:
  apiKey: $PACKET_API_KEY
  projectID: $PACKET_PROJECT_ID
type: Opaque
