apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: packetmachineproviderspecs.packetprovider.k8s.io
spec:
  group: packetprovider.k8s.io
  names:
    kind: PacketMachineProviderSpec
    plural: packetmachineproviderspecs
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        OS:
          type: string
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        billingCycle:
          type: string
        facility:
          items:
            type: string
          type: array
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        machineType:
          type: string
        metadata:
          type: object
        projectID:
          type: string
        roles:
          items:
            type: string
          type: array
        sshKeys:
          items:
            type: string
          type: array
      required:
      - OS
      - projectID
      - billingCycle
      - machineType
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
