[package]
name = "zip321"
description = "Parsing functions and data types for Zcash ZIP 321 Payment Request URIs"
version = "0.0.0"
authors = [
    "Kris Nuttycombe <kris@electriccoin.co>"
]
homepage = "https://github.com/zcash/librustzcash"
repository.workspace = true
readme = "README.md"
license.workspace = true
edition.workspace = true
rust-version.workspace = true
categories.workspace = true

[dependencies]
