[package]
name = "zip32"
version = "0.0.0"
authors = [
    "Jack Grigg <jack@electriccoin.co>",
    "Kris Nuttycombe <kris@electriccoin.co>",
]
description = "Library for implementing shielded hierarchical deterministic wallets"
documentation = "https://docs.rs/zip32/"
homepage = "https://github.com/zcash-hackworks/zip32"
repository = "https://github.com/zcash-hackworks/zip32"
license.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
blake2b_simd.workspace = true
memuse.workspace = true
subtle.workspace = true

[dev-dependencies]
assert_matches.workspace = true
