[package]
name = "zcash_proofs"
version = "0.0.0"
authors = [
    "Jack Grigg <jack@z.cash>",
]

[dependencies]
bellman = { path = "../bellman" }
byteorder = "1"
ff = "0.4"
pairing = { path = "../pairing" }
rand = "0.4"
sapling-crypto = { path = "../sapling-crypto" }
