[package]
name = "zcash_client_backend"
description = "APIs for creating shielded Zcash light clients"
version = "0.2.0"
authors = [
    "Jack Grigg <jack@z.cash>",
]
homepage = "https://github.com/zcash/librustzcash"
repository = "https://github.com/zcash/librustzcash"
readme = "README.md"
license = "MIT OR Apache-2.0"
edition = "2018"

[dependencies]
bech32 = "0.7"
bls12_381 = { version = "0.1", path = "../bls12_381" }
bs58 = { version = "0.3", features = ["check"] }
ff = { version = "0.7", path = "../ff" }
group = { version = "0.7", path = "../group" }
hex = "0.4"
jubjub = { version = "0.3", path = "../jubjub" }
protobuf = "=2.14.0" # 2.15 has MSRV of 1.44.1
subtle = "2"
zcash_primitives = { version = "0.2", path = "../zcash_primitives" }

[build-dependencies]
protobuf-codegen-pure = "2.14"

[dev-dependencies]
rand_core = "0.5"
rand_xorshift = "0.2"

[badges]
maintenance = { status = "actively-developed" }
