[package]
name = "zcash_client_backend"
description = "APIs for creating shielded Zcash light clients"
version = "0.5.0"
authors = [
    "Jack Grigg <jack@z.cash>",
    "Kris Nuttycombe <kris@electriccoin.co>"
]
homepage = "https://github.com/zcash/librustzcash"
repository = "https://github.com/zcash/librustzcash"
readme = "README.md"
license = "MIT OR Apache-2.0"
edition = "2018"

[dependencies]
bech32 = "0.8"
bls12_381 = "0.6"
bs58 = { version = "0.4", features = ["check"] }
base64 = "0.13"
ff = "0.11"
group = "0.11"
hex = "0.4"
jubjub = "0.8"
nom = "7"
percent-encoding = "2.1.0"
proptest = { version = "1.0.0", optional = true }
protobuf = ">=2.20,<2.26" # protobuf 2.26 bumped MSRV to 1.52.1
rand_core = "0.6"
subtle = "2.2.3"
time = "0.2"
zcash_note_encryption = { version = "0.1", path = "../components/zcash_note_encryption" }
zcash_primitives = { version = "0.5", path = "../zcash_primitives" }

[build-dependencies]
protobuf-codegen-pure = ">=2.20,<2.26" # protobuf 2.26 bumped MSRV to 1.52.1

[dev-dependencies]
gumdrop = "0.8"
rand_xorshift = "0.3"
tempfile = "3.1.0"
zcash_client_sqlite = { version = "0.3", path = "../zcash_client_sqlite" }
zcash_proofs = { version = "0.5", path = "../zcash_proofs" }

[features]
test-dependencies = ["proptest", "zcash_primitives/test-dependencies"]

[lib]
bench = false

[badges]
maintenance = { status = "actively-developed" }
