---
on:
  push:
    branches:
    - master
    tags:
    - v*
  pull_request:
    branches:
    - master
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.15.11, 1.16.2]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install dependencies
      run: GO111MODULE=off go get golang.org/x/lint/golint
    - name: Compile
      run: make build
    - name: Lint
      run: make lint
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v2
      with:
        version: v1.38.0
        skip-go-installation: true
        skip-pkg-cache: true
        skip-build-cache: true
    - name: Test
      run: make test-unit
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        fail_ci_if_error: true
        files: ./coverage.txt
        verbose: true
  deploy:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Prepare
        id: prep
        run: |
          echo "BRANCH=$(git symbolic-ref --short -q HEAD || echo HEAD)" >> $GITHUB_ENV                          # for goreleaser
          echo "COMMIT=$(git rev-parse HEAD)" >> $GITHUB_ENV                                                     # for goreleaser
          echo "DATE=$(date -u +%Y%m%d-%H:%M:%S)" >> $GITHUB_ENV                                                 # for goreleaser
          echo "VERSION_PKG=github.com/KohlsTechnology/blackbox-helloworld-responder/pkg/version" >> $GITHUB_ENV # for goreleaser
          DOCKER_IMAGE=quay.io/kohlstechnology/blackbox-helloworld-responder
          VERSION=${GITHUB_REF#refs/tags/}
          TAGS="${DOCKER_IMAGE}:${VERSION},${DOCKER_IMAGE}:latest"
          echo ::set-output name=tags::${TAGS}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to quay.io
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.QUAY_USER }}
          password: ${{ secrets.QUAY_TOKEN }}
          registry: quay.io
      - name: Build and push to quay.io
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.prep.outputs.tags }}
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
