---
on:
  push:
    branches:
    - master
    tags:
    - v*
  pull_request:
    branches:
    - master
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.15.8, 1.16.2]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install dependencies
      run: GO111MODULE=off go get golang.org/x/lint/golint
    - name: Compile
      run: make build
    - name: Lint
      run: make lint
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v2
      with:
        version: v1.38.0
        skip-go-installation: true
        skip-pkg-cache: true
        skip-build-cache: true
    - name: Test
      run: make test-unit
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        fail_ci_if_error: true
        files: ./coverage.txt
        verbose: true
  deploy:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Push to quay.io
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.QUAY_USER }}
          password: ${{ secrets.QUAY_TOKEN }}
          registry: quay.io
          repository: kohlstechnology/blackbox-helloworld-responder
          tag_with_ref: true
