name: Pull Request E2E
on:
 workflow_run:
   workflows: ["Pull Request Validation"]
   types: [completed]
jobs:
  e2e-smoketest:
    name: E2E Smoketest
    runs-on: ubuntu-latest
    if: >
      ${{ github.event.workflow_run.event == 'pull_request' &&
      github.event.workflow_run.conclusion == 'success' }}
    steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Setup kind
      uses: engineerd/setup-kind@v0.5.0
      with:
        version: v0.11.1
        skipClusterCreation: true
    - name: 'Download artifact'
      uses: actions/github-script@v4.1
      with:
        script: |
          var artifacts = await github.actions.listWorkflowRunArtifacts({
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: ${{github.event.workflow_run.id }},
          });
          var matchArtifact = artifacts.data.artifacts.filter((artifact) => {
            return artifact.name == "e2e-artifacts"
          })[0];
          var download = await github.actions.downloadArtifact({
              owner: context.repo.owner,
              repo: context.repo.repo,
              artifact_id: matchArtifact.id,
              archive_format: 'zip',
          });
          var fs = require('fs');
          fs.writeFileSync('${{github.workspace}}/e2e-artifacts.zip', Buffer.from(download.data));
    - run: unzip e2e-artifacts.zip
    - name: Load image
      run: |
        docker load --input capp-e2e-image.tar
        docker image ls -a
    - name: e2e smoketest
      env:
        PACKET_API_KEY: ${{ secrets.PACKET_API_TOKEN }}
        PROJECT_ID: ${{ secrets.PROJECT_ID }}
      # This currently runs the tests serially, if we need to parallize
      # need to install ginkgo and use it to run the tests
      run: |
        chmod +x e2e.test
        ./e2e.test -e2e.artifacts-folder=${PWD}/artifacts -e2e.config=config/e2e-config.yaml -ginkgo.focus='\[Smoke Test\]' -ginkgo.progress -ginkgo.trace -ginkgo.v
