name: goreleaser

on:
  push:
    branches-ignore:
      - "**"
    tags:
      - "v*.*.*"

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: "Unshallow (required by goreleaser)"
        run: git fetch --prune --unshallow
      - name: Get the version
        run: echo ::set-env name=VERSION::${GITHUB_REF/refs\/tags\//}
      - uses: azure/docker-login@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.14.x
      - name: install kustomize
        uses: imranismail/setup-kustomize@v1
        with:
          kustomize-version: "3.5.4"
      - name: Set up Docker Buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          buildx-version: latest
          qemu-version: latest
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2.0.2
        with:
          version: latest
          args: release --rm-dist --debug
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Update docker manifest
        run: |
          buildx imagetools create \
            -t packethost/cluster-api-provider-packet:$VERSION \
            packethost/cluster-api-provider-packet:$VERSION-amd64 \
            packethost/cluster-api-provider-packet:$VERSION-arm64
