name: Rust

on: [push]

jobs:
  test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v1
    - name: Check formatting
      run: cargo fmt --all -- --check
    - name: Build
      run: cargo build --verbose --release --all
    - name: Run tests
      run: cargo test --verbose --release --all
